# -*- coding: utf-8 -*-
"""forced_aligner_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PwWiKjFJw1pviFrOdWgqR8UZfzi9_wXe

# Preliminaries

This file provides the code for two different tasks for preparing Montreal Forced Aligner input:
  1.   Process textgrids-strip punctuation, convert numbers to text, [etc.](https://colab.research.google.com/drive/1PwWiKjFJw1pviFrOdWgqR8UZfzi9_wXe#scrollTo=ql7jRThi6HMT&line=7&uniqifier=1)
  2.   Generate pronunciation dictionary
  *   MFA dictionaries are formatted as tab-separated pairs of orthographic and phonemic representations. An example entry looks like this:
  *   شمس	sh a m s

You will need some sort of utterance-level transcript. These can be .TextGrid or .txt, but must be encoded in UTF-8. For TextGrids, each utterance needs timestamps. For text files, each utterance should be on a new line. The .txt format really only works with short files (a few minutes or less), because if the aligner gets thrown off, there is no timestamp to get it back on track.

This code makes extensive use of the CAMeLTools package. [To install CAMeLTools for the first time]('https://colab.research.google.com/drive/1Y3qCbD6Gw1KEw-lixQx1rI6WlyWnrnDS?usp=sharing'), set the variable first_run below to 'True'. For more information on CAMeLTools, see [here]('https://camel-tools.readthedocs.io/en/latest/index.html').
"""

#if you need to install cameltools, toggle this to true
first_run = False

"""Change the following directory paths to where your data is. The default, /content/ is a temporary folder that will be deleted when the runtime disconnects. You can also link to files in your Google Drive."""

#input directory-tell python where your textgrids are
input_directory = '/content/TGS/'
#output directory-tell python where to send your processed textgrids
output_directory = '/content/TGS/TGS_processed/'
#output_directory_dict-tell python where to save dictionary and other files
output_directory_dict = '/content/'

"""This code generates up to seven files. You can toggle off some of these options below. Here you can change the file names without wading through the code.
1.   Dictionary: this is a list of orthographic forms, transcriptions, and morphological information. This is the building block for the rest of the script.
2.   Filtered dictionary: A subset of the dictionary with certain forms removed based on the morphological information in 1.
3.   Processed dict: An expansion of the filtered dictionary, adding new entries with different grapheme-phoneme correspondences
4.   Processed dict_l: The processed dictionary without pharyngealized /l/ except when لله is in the orthographic form.
  *   If you include this script, processed_dict_l will be the final version fo your MFA dictionary. Otherwise, processed_dict will be the final dictionary.
5.   OOV list: list of orthographic forms not found (out of vocabulary) in the morphological analyzer.
6.   New OOV list: a subset of the OOV list also not present in a second morphological analyzer.
7. Dialect predictions: lists the most likely city, country, and region for each textgrid, along with the likelihood.

Note on file formats:
The final dictionary should be in .dict format. This is the format used by MFA dictionaries, and is basically the same as a TSV. MFA dictionaries *must* be tab-separated, so CSVs will not work.
The other files are in .txt, but don't necessarily need to be.
"""

#file names
dictionary = 'dictionary_entries.txt'
filtered_dictionary = 'filtered_dictionary_entries.tsv'
processed_dict = 'processed_dict.dict'
processed_dict_l = 'processed_dict_l.dict'
dialect_predictions_list = 'dialect_predictions.txt'
oov_list = 'oovs.txt'
new_oov_list = 'new_oovs.txt'

"""#Pre-processing

The processing code has a number of functions:


1.   Removes voweled text. I chose to do this to reduce the number of pronunciations for any given orthographic form by excluding ʾiʿrāb/declensions. How this works:
   * Compares original line of text in TextGrid to dediacritized line, and counts the number of words that are different. If every word in the line is different, the entire line is blanked out and replaced with '٭', which maintains right to left text direction.
   *   The same comparison applies to text between some sort of bracket (quotation marks, parentheses), and can also handle bracketed text that spans multiple lines.
   *  Words that are diacritized for clarity in otherwise unvoweled lines are not removed, but will be dediacritized.

2. [Strips](https://camel-tools.readthedocs.io/en/latest/api/utils/dediac.html) diacritics except for أ, إ, آ, ؤ
3. [Normalizes](https://camel-tools.readthedocs.io/en/latest/api/utils/normalize.html) letter forms/calligraphy  
4.   Strips punctuation, including [emojis](https://camel-tools.readthedocs.io/en/latest/api/utils/charsets.html).
5.   [Converts](https://pyarabic.readthedocs.io/ar/latest/features.html#id6) digits/years to words. This has several bugs:  

      *   Numbers conjoined with text are converted to 0. So an abbreviation like 4كم will become 'صفر'.
      *   This script has to occur after punctuation is stripped, so it does not correctly encode decimals/percents
      *   Defaults to nominative case (20 becomes عشرون, not عشرين)
6.   Replaces repeated characters with just one instance (يا شباااااااااب becomes يا شباب)
7.   Gets rid of citations of religious texts. My dataset had several examples of Biblical citations in the subtitles that the speaker didn't actually say. You probably don't need this, but could be converted into a more generic text filter.
"""

#options
#remove fully voweled text
remove_diacritized_text = True
remove_citations = False

"""# Morphology and Filtering

After the text is processed, the script generates a dictionary with all of the pronunciations in the chosen morphological database. It also includes morphological information, which can be used to filter out entries.

There are two [morphological databases](https://camel-tools.readthedocs.io/en/latest/api/morphology/database.html#camel-morphology-dbs) to choose from, MSA and Egyptian. You can also use both. These are currently the only two options because they are the only databases that produce transcriptions (MSA) or diacritized forms (Egyptian).

The Egyptian database produces only a diacritized form, which is then converted to Buckwalter. However, the [ar2bw function](https://camel-tools.readthedocs.io/en/latest/cli/camel_transliterate.html?highlight=ar2bw) assumes MSA pronunciation. The goal of including Egyptian at this stage is not to get accurate transcriptions, but to ensure that common cross-dialectal word forms (مافي, ليش) are not treated as out-of-vocabulary tokens.
"""

#morphology database
morph_db_msa = True #will break code if set to false
morph_db_egy = True

"""The default dictionary entry includes the following information taken from the CaMeLTools morphological analyzer. This list cannot be edited (yet):
See https://camel-tools.readthedocs.io/en/latest/reference/camel_morphology_features.html for more information on tags.

1.   Arabic word (dediacritized)
2.   Arabic word (diacritized)
3.   Part of speech tag
4.   Voice tag
5.   Mood tag
6.   Case tag
7. State tag
8.   Buckwalter transcription
9.   Caphi transcription

You can filter out various things: (currently you can choose to filter/not filter, but the individual items can't be modified)
  *   Passive voice
  *   Subjunctives
  *   Case markings (maintains some)

The entry is not filtered out if it is the only instance of the orthographic form in the dictionary.

You can also include additional forms of the definite article with the glottal stop and vowel removed:
  *   2 a l q a m r / 2 a sh sh a m s (default)
  *   a l q a m r / a sh sh a m s (added)
  *   l q a m r / sh sh a m s (added)

The code also adds /t/ - final forms of feminine nouns ending in 'ة' if their "state" tag is "c" (for construct/possessive/idaafa)
"""

#choose whether you want the following things included:
passives = False
subjunctives = False
case_markings = False
def_variations = True #this generates new entries with the definite article reduced
t_final_taa_marbuta = True

#other options:
dialect_predictions = True #generates regional, national, and metropolitan-level dialect predictions
punctuation = '[()\[\]<—>{}/\»«﴾﴿*♪:؛.!\'‘’”“#؟•+%٪\t_،,-]' #set of punctuation to be stripped

"""#Grapheme-Phoneme Correspondences

Uncomment your preferred epenthesis site for CCC clusters. This adds new entries, but does not remove the CCC entry.
"""

#triconsonantal epenthesis-uncomment the one you want.
#epenthesis_site = 'CCVC'
#epenthesis_site = 'CVCC'
epenthesis_site = 'both'

"""Choose whether you want new entries for coda cluster epenthesis and short vowel deletion (syncope has not been coded yet, so this variable doesn't do anything)."""

coda_cluster_epenthesis = True #creates new entries with /i/ between two final consonants
syncope = False

"""Choose whether you want monophthongization and l. deletion.

Deletion of l. removes dictionary entries with /l./ unless 'لله' exists in the orthography. You probably want to do this unless you know you have extensive l-pharyngealization.

Although /e/ and /o/ exist in the forced alignment models, there's currently no way to generate dictionary entries that include them other than writing them manually. I'm not sure if the model actually learned these phones, since it didn't see any examples.
"""

monophthongization = True #creates new entries with /aw/ -> /oo/ and /aj/ -> /ee/
l_filtering = True #removes l. entries unless لله in orthography.

"""Change the following alphabet code to match the grapheme-phoneme correspondences in your data. The MFA models use the [CAPHI transcription system](https://camel-guidelines.readthedocs.io/en/latest/phonology/#5-caphi-phonetic-inventory).

There are two alphabets provided:

The defaults are the most common, and the commented-out phones are all of the grapheme-phoneme correspondences listed in CAPHI (exception: digraphs acting as affricates, such as 'تش' for 'tsh'). I don't recommend using the full phone set unless you have a good reason because it exponentially increases the number of dictionary entries.

The forced aligner will only work if the phone set is the same/a subset of the phone set used to train it. However, the grapheme-phoneme correspondences don't need to be the same.

Full CAPHI consonant set: b, b., d, d., dh, dh., dj, dz, f, f., g, gh, gy, h, j, k, kh, l, l., m, m., n, n., p, p., q, qh, r, r., s, s., sh, t, t., th, ts, tsh, v, z, z., 2, 3, 7

Reduced set excludes dz, f., gy, m., n., p, p., qh, r., ts, tsh, v

Full glide/vowel set: w, y, aa, ee, ii, oo, uu, a, e, i, o, u

Reduced vowel set excludes mid vowels

*   Model 1: full consonant set + reduced vowel set
*   Model 2: reduced consonant set + full vowel set
*   Model 3: full consonant set + full vowel set

When you preview the dictionary, you might see entries that look like 'علينا	3 a l ee n aa'. This is just a display issue and won't affect future processing (ان شاء اللّٰه).
"""

alphabet = [
('ب' , ['b', 'b.']), #['b', 'b.', 'p', 'p.']
('ت' , ['t']), #['t', 'd', 't.', 'd.']
('ث' , ['th', 's', 't']),
('ج' , ['j', 'dj', 'y', 'g']), #['dj', 'g', 'gy', 'j', 'dz', 'ts', 'tsh', 'y']
('ح' , ['7']),
('خ' , ['kh']),
('د' , ['d']), #['d', 'd.']
('ذ' , ['dh', 'd', 'z']), #['dh', 'd', 'dh.', 'z']
('ر' , ['r', 'gh']), #['r', 'r.', 'gh']
('ز' , ['z']), #['z', 's', 'z.']
('س' , ['s']), #['s', 's.', 'z']
('ش' , ['sh']), #['sh', 'tsh']
('ص' , ['s.']), #['s.', 's', 'z']
('ض' , ['d.']), #['d.', 'd', 'dh.', 'z.']
('ط' , ['t.']),
('ظ' , ['dh.', 'z.', 'd.']),
('ع' , ['3']),
('غ' , ['gh']), # ['gh', 'kh']
('ف' , ['f']), #['f', 'f.', 'v']
('ق' , ['q', '2', 'g', 'dj']), #['q', 'qh', '2', 'dj', 'dz', 'g', 'j', 'k']
('ك' , ['k']), #['k', 'g', 'ts']
('ل' , ['l', 'l.']),
('م' , ['m']), #['m', 'm.']
('ن' , ['n']), #['n', 'n.']
('ه', ['h'])
]

alphabet_letters_ar = ['ب', 'ت', 'ث', 'ج', 'ح', 'خ', 'د', 'ذ', 'ر', 'ز', 'س', 'ش', 'ص', 'ض', 'ط', 'ظ', 'ع', 'غ', 'ف', 'ق', 'ك', 'ل', 'م', 'ن', 'ه']

"""# The Code (messy)"""

# Commented out IPython magic to ensure Python compatibility.
# @title
# install cameltools for the first time
if first_run == True:
#   %pip install pyarabic
#   %pip install camel-tools
  from google.colab import drive
  import os

  drive.mount('/gdrive')

#   %mkdir /gdrive/MyDrive/camel_tools
  os.environ['CAMELTOOLS_DATA'] = '/gdrive/MyDrive/camel_tools'

  !export | camel_data -i all

# Commented out IPython magic to ensure Python compatibility.
# @title
#read in packages
import re
import os
import itertools
from os import listdir
from os.path import isfile, join

# %pip install pyarabic
import pyarabic.araby as araby
import pyarabic.number as number
import pyarabic.trans

# %pip install camel-tools

from google.colab import drive
import os

drive.mount('/gdrive')
os.environ['CAMELTOOLS_DATA'] = '/gdrive/MyDrive/camel_tools'

import camel_tools
from camel_tools.utils.normalize import normalize_unicode
from camel_tools.morphology.database import MorphologyDB
from camel_tools.morphology.analyzer import Analyzer
from camel_tools.utils.dediac import dediac_ar
from camel_tools.dialectid import DialectIdentifier
from camel_tools.utils.charmap import CharMapper
from camel_tools.utils.charsets import EMOJI_ALL_CHARSET

if morph_db_msa == True:
  #load morphological analyzer for MSA
  db = MorphologyDB.builtin_db('calima-msa-r13')
  analyzer = Analyzer(db)
elif morph_db_egy == True and morph_db_msa == False:
  db = MorphologyDB.builtin_db('calima-egy-r13')
else:
  print('Error: Please choose a morphological database.')

#add buckwalter transcription system
ar2bw = CharMapper.builtin_mapper('ar2bw')
#for integer to text
an = number.ArNumbers()

import pandas as pd
import numpy as np
from string import Template

# @title
#splitting function: https://sqlpey.com/python/python-string-split-keep-delimiters/
def split_string_with_separators(regex_pattern, text_content):
   # Compile the regex pattern for efficiency
   separator_regex = re.compile(regex_pattern)

   # Split the string using the regex
   split_parts = separator_regex.split(text_content)

   resulting_list = []
   current_pos = 0
   for part in split_parts:
     if not part: continue # Skip empty parts if any

     # Find the position of the current part in the original string
     found_pos = text_content.find(part, current_pos)

     # If there's content before the current part, and it's not the same as the last appended item, add it
     if found_pos > current_pos and (not resulting_list or resulting_list[-1] != text_content[current_pos:found_pos]):
       resulting_list.append(text_content[current_pos:found_pos])

     resulting_list.append(part)
     current_pos = found_pos + len(part)

   # Add any remaining content at the end
   if current_pos < len(text_content):
     resulting_list.append(text_content[current_pos:])

   return resulting_list

#set up lists
emoji_list = []
for emoji in EMOJI_ALL_CHARSET:
  if len(emoji) == 1:
    emoji_list.append(emoji)

subtitle_org = ['٠','١','٢','٣','٤','٥','٦','٧','٨','٩','0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
#be very careful messing with the bracket regex-it breaks easily so test modifications before implementing
brackets = r'[()\[\]<—>{}/\»«﴾﴿*♪:؛.!\'‘’”“#؟•+%٪\t_،,-]'
opening_brackets = '’”’’«﴾<[{(\'*♪'
closing_brackets = '‘“‘‘»﴿>]})\'*♪'
text_errors = ['&rlm;', '&nbsp;', '&gt;', '&amp;', '&lt;']
#numbers = ['٠','١','٢','٣','٤','٥','٦','٧','٨','٩']
quran_diac = ['ٱلْفَاتِحَة','ٱلْحَمْد','ٱلْأَسَاس','ٱلسّبْعُ الْمَثَانِي','ٱلْبَقَرَة','آلِ عِمْرَان','ٱلنِّسَاء','ٱلْمَائِدَة','ٱلْعُقُود','ٱلْأَنْعَام','ٱلْأَعْرَاف','ٱلْأَنْفَال','بَدْر','ٱلتَّوْبَة','بَرَاءَة','يُونُس','هُود','يُوسُف','ٱلرَّعْد','إِبْرَاهِيم','ٱلْحِجْر','ٱلنَّحْل','اٌلاِسْرٰاء','بَنِي إِسْرَائِيل','ٱلْكَهْف','مَرْيَم','ٱلْكَلِيم','ٱلْأَنْبِيَاء','ٱلْحَجّ','ٱلْمُؤْمِنُون','ٱلنُّور','ٱلْفُرْقَان','ٱلشُّعَرَاء'
,'ٱلنَّمْل','سُلَيْمَان','ٱلْقَصَص','ٱلْعَنْكَبُوت','ٱلرُّوم','لُقْمَان','ٱلسَّجْدَة','ٱلْمَضَاجِع','ٱلْأَحْزَاب','سَبَأ','فَاطِر','ٱلْمَلَائِكَة','ٱلصَّافَّات','دَاوُد','ٱلزُّمَر','ٱلْغُرَف','غَافِر','ٱلْمُؤْمِن'
,'فُصِّلَت','ٱلْمَصَابِيح','ٱلشُّورىٰ','ٱلزُّخْرُف','ٱلدُّخَان','ٱلْجَاثِيَة','ٱلشَّرِيعَة','ٱلْأَحْقَاف','مُحَمَّد','ٱلْقِتَال','ٱلْفَتْح','ٱلْحُجُرَات','ٱلْبَاسِقَات','ٱلذَّارِيَات','ٱلطُّور','ٱلنَّجْم','ٱلْقَمَر','ٱقْتَرَبَت','ٱلرَّحْمَٰن','ٱلْوَاقِعَة','ٱلْحَدِيد','ٱلْمُجَادِلَة','ٱلظِّهَار','ٱلْحَشْر','ٱلْمُمْتَحَنَة','ٱلصَّفّ','ٱلْحَوَارِيِّين','ٱلْجُمُعَة','ٱلْمُنَافِقُون','ٱلتَّغَابُن','ٱلطَّلَاق','ٱلتَّحْرِيم','لِمَتُحَرِّم','ٱلْمُلْك','تَبَارَك','ٱلْقَلَم','ٱلْحَاقَّة','ٱلْمَعَارِج','سَأَلَسَائِل','نُوح','ٱلْجِنّ','ٱلْجِنّ','ٱلْمُزَّمِّل','ٱلْمُدَّثِّر','ٱلْقِيَامَة','ٱلْإِنْسَان','ٱلْمُرْسَلَات','ٱلنَّبَأ','عَمَّ','ٱلنَّازِعَات','ٱلسَّاهِرَة','عَبَسَ','ٱلسَّفَرَ','ٱلتَّكْوِير','ٱلْإِنْفِطَار','ٱلْمُطَفِّفِين','ٱلْإِنْشِقَاق','ٱلْبُرُوج','ٱلطَّارِق','ٱلْأَعْلَىٰ','ٱلْغَاشِيَة','ٱلْفَجْر','ٱلْبَلَد','ٱلشَّمْس','ٱللَّيْل','ٱلضُّحَىٰ','ٱلشَّرْح','ٱلتِّين','ٱلْعَلَق','ٱلْقَدْر','ٱلْبَيِّنَة','أَهْلُالْكِتَاب','ٱلزَّلْزَلَة','ٱلْقَارِعَة'
,'ٱلتَّكَاثُر','ٱلْعَصْر','ٱلْهُمَزَة','ٱلْفِيل','قُرَيْش','ٱلْمَاعُون','ٱلدِّين','ٱلْكَوْثَر','ٱلْكَافِرُون','ٱلْعِبَادَة','ٱلنَّصْر','ٱلتَّوْدِيع','ٱلْمَسَد','تَبَّت','ٱلْإِخْلَاص','ٱلتَّوْحِيد','ٱلْفَلَق','ٱلنَّاس']
quran_dediac = ['ٱلفاتحة', 'ٱلحمد', 'ٱلأساس', 'ٱلسبع المثاني', 'ٱلبقرة', 'آل عمران', 'ٱلنساء', 'ٱلمائدة', 'ٱلعقود', 'ٱلأنعام', 'ٱلأعراف', 'ٱلأنفال', 'بدر', 'ٱلتوبة', 'براءة', 'يونس', 'هود', 'يوسف', 'ٱلرعد', 'إبراهيم', 'ٱلحجر', 'ٱلنحل', 'الاسراء', 'بني إسرائيل', 'ٱلكهف', 'مريم', 'ٱلكليم', 'ٱلأنبياء', 'ٱلحج', 'ٱلمؤمنون', 'ٱلنور', 'ٱلفرقان', 'ٱلشعراء', 'ٱلنمل', 'سليمان', 'ٱلقصص', 'ٱلعنكبوت', 'ٱلروم', 'لقمان', 'ٱلسجدة', 'ٱلمضاجع', 'ٱلأحزاب', 'سبأ', 'فاطر', 'ٱلملائكة', 'ٱلصافات', 'داود', 'ٱلزمر', 'ٱلغرف', 'غافر', 'ٱلمؤمن', 'فصلت', 'ٱلمصابيح', 'ٱلشورى', 'ٱلزخرف', 'ٱلدخان', 'ٱلجاثية', 'ٱلشريعة', 'ٱلأحقاف', 'محمد', 'ٱلقتال', 'ٱلفتح', 'ٱلحجرات', 'ٱلباسقات', 'ٱلذاريات', 'ٱلطور', 'ٱلنجم', 'ٱلقمر', 'ٱقتربت', 'ٱلرحمن', 'ٱلواقعة', 'ٱلحديد', 'ٱلمجادلة', 'ٱلظهار', 'ٱلحشر', 'ٱلممتحنة', 'ٱلصف', 'ٱلحواريين', 'ٱلجمعة', 'ٱلمنافقون', 'ٱلتغابن', 'ٱلطلاق', 'ٱلتحريم', 'لمتحرم', 'ٱلملك', 'تبارك', 'ٱلقلم', 'ٱلحاقة', 'ٱلمعارج', 'سألسائل', 'نوح', 'ٱلجن', 'ٱلجن', 'ٱلمزمل', 'ٱلمدثر', 'ٱلقيامة', 'ٱلإنسان', 'ٱلمرسلات', 'ٱلنبأ', 'عم', 'ٱلنازعات', 'ٱلساهرة', 'عبس', 'ٱلسفر', 'ٱلتكوير', 'ٱلإنفطار', 'ٱلمطففين', 'ٱلإنشقاق', 'ٱلبروج', 'ٱلطارق', 'ٱلأعلى', 'ٱلغاشية', 'ٱلفجر', 'ٱلبلد', 'ٱلشمس', 'ٱلليل', 'ٱلضحى', 'ٱلشرح', 'ٱلتين', 'ٱلعلق', 'ٱلقدر', 'ٱلبينة', 'أهلالكتاب', 'ٱلزلزلة', 'ٱلقارعة', 'ٱلتكاثر', 'ٱلعصر', 'ٱلهمزة', 'ٱلفيل', 'قريش', 'ٱلماعون', 'ٱلدين', 'ٱلكوثر', 'ٱلكافرون', 'ٱلعبادة', 'ٱلنصر', 'ٱلتوديع', 'ٱلمسد', 'تبت', 'ٱلإخلاص', 'ٱلتوحيد', 'ٱلفلق', 'ٱلناس']


bible_nondiac = ['تكوين','خروج','لاويين','عدد','تثنية','يشوع','قضاه','راعوث','صموئيل','ملوك','أخبار أيام','عزرا','نحميا','طوبيت','يهوديت','أستير','مكابيين','أيوب','مزامير','أمثال','الجامعة','نشيد الأنشاد','الحكمة','سيراخ','إشعياء','إرميا','مراثي ارميا','نبوة باروخ','حزقيال','دانيال','هوشع','يوئيل','عاموس','عوبديا','يونان','ميخا','ناحوم','حبقوق','صفنيا','حجي','زكريا','ملاخي','متى','مرقس','لوقا','يوحنا','يوحنَّا','أعمال الرسل','أعمال','رومية','كورنثوس','غلاطية','أفسس','فيلبى','كولوسي','تسالونيكي','تيموثاوس','تيطس','فليمون','عبرانيين','يعقوب','بطرس','يهوذا','رؤيا, ''أعمال']

base_dict = []
dictionary_entries = []
oovs = []
word_list = []
dialect_ids = []
#loop through files in input direct
##open file
file_list = [f for f in listdir(input_directory) if isfile(join(input_directory, f))]
for f in file_list:
  text = []
  processed_copy = []
  with open(join(input_directory, f), mode = 'r') as g:
##remove textgrid formatting, quotation marks, and blank lines
      for raw_line in g:
        if '            text = "' in raw_line and raw_line != '            text = " "\n':
          line = raw_line[20:-2]
#this section removes voweled text
##start by normalizing and diacritizing text
          line = normalize_unicode(line)
          line_dediac_1 = dediac_ar(line)
#split conjoined arabic and latin text with a space
          q_line = pyarabic.trans.segment_language(line)
          if len(q_line) > 1:
            line = ' '.join(w[1] for w in q_line)
          q_line_dediac_1 = pyarabic.trans.segment_language(line_dediac_1)
          if len(q_line_dediac_1) > 1:
            line_dediac_1 = ' '.join(w[1] for w in q_line_dediac_1)
#insert spaces between punctuation marks-these will be removed later
          line = split_string_with_separators(brackets, line)
          line_dediac_1 = split_string_with_separators(brackets, line_dediac_1)
          words = [l.split(' ') for l in line]#split on whitespace
          words = list(itertools.chain(*words)) #flatten into one list
          words = [x for x in words if x != ''] #remove empty strings
          line_dediac = [l.split(' ') for l in line_dediac_1]
          line_dediac = list(itertools.chain(*line_dediac))
          line_dediac = [x for x in line_dediac if x!= '']
          diff_count = 0
##compare text to dediacritized text. the difference count increases for each word with diacritics. here to line 146 need to be fixed
          if remove_diacritized_text == True:
            for word, word_dediac in zip(words, line_dediac):
              if word != word_dediac:
                diff_count += 1
##if every word in the line is diacritized, replace the entire line with a star
            if diff_count == len(words):
              line_dediac = (' ٭' for word_dediac in line_dediac)
              line_dediac = ' '.join(line_dediac)
##handles lines that are partially diacritized, such as quotes in brackets.
###if there is at least one difference, and some sort of bracket in the line, split the line using the bracket as a delimiter, then also split on spaces and flatten the list so brackets are separate list entries
            elif any(bracket in line_dediac_1 for bracket in brackets):
              line_dediac_split = line_dediac
              line_split = line
              opening_index = -1
              closing_index = -1
###gets the index of opening and closing brackets
              for index, word in enumerate(line_split): #list goes right-to-left
                if word in opening_brackets and opening_index == -1:
                  opening_index = index
                elif word in closing_brackets:
                  closing_index = index
              bracket_diff = 0
              if diff_count > 0:
                if closing_index > 0 and opening_index >= 0: #if the bracket opens and closes in line
                  for idx in range(opening_index+1, closing_index):
                    if line_dediac_split[idx] != line_split[idx]: #if there's a difference between words in between the brackets
                      bracket_diff += 1
                      if bracket_diff == closing_index - (opening_index+1): #if every word in brackets is diacritized, replace all words
                        for idx in range(opening_index+1, closing_index):
                          line_dediac_split[idx] = ' ٭'
###handles quotes spread across multiple lines-if there's a bracket at the edge of the line, it flips from right-to-left to left-to-right.
                elif closing_index == -1 and opening_index >= 0: #if opening bracket only also handles line-final closing brackets
###check to see if the previous word is diacritized, then it's actually a closing bracket
                  if opening_index > 0 and line_dediac_split[opening_index-1] != line_split[opening_index-1]:
                    closing_index = opening_index
                    opening_index = -1
                    for idx in range(0, closing_index):
                      if line_dediac_split[idx] != line_split[idx]:
                        bracket_diff += 1
                    if bracket_diff == closing_index:
                      for idx in range(0, closing_index):
                        line_dediac_split[idx] = ' ٭'
                  else:
                    for idx in range(opening_index+1, len(line_split)):
                      if line_dediac_split[idx] != line_split[idx]:
                        bracket_diff += 1
                    if bracket_diff == len(line_split) - (opening_index+1):
                      for idx in range(opening_index + 1, len(line_split)):
                        line_dediac_split[idx] = ' ٭'
                elif closing_index > 0 and opening_index == -1: #if closing bracket only-also handles line-initial opening brackets
                  for idx in range(0, closing_index):
                    if line_dediac_split[idx] != line_split[idx]:
                      bracket_diff += 1
                  if bracket_diff == closing_index:
                    for idx in range(0, closing_index):
                      line_dediac_split[idx] = ' ٭'
###replaces unspoken citations of religious texts
              if remove_citations == True:
                for idx in range(len(line_dediac_split)):
                  opening_index = -1
                  closing_index = -1
                  if line_dediac_split[idx] in bible_nondiac or line_dediac_split[idx] in quran_dediac:
                    opening_index = idx
                    for idx in range(opening_index, len(line_dediac_split)):
                      if any(number in line_dediac_split[idx] for number in subtitle_org): #can't deal with numbers other than 0-9
                        closing_index = idx
                      if opening_index != -1 and closing_index != -1:
                        for idx in range(opening_index, closing_index + 1):
                          line_dediac_split[idx] = ' ٭'
              line_dediac = line_dediac_split
###convert other numbers to text
            for idx in range(len(line_dediac)): #j = word text
              if any(number in line_dediac[idx] for number in subtitle_org):
                k = an.int2str(line_dediac[idx])
                if k == 'صفر': #if combined number and text, int2str will return 0.
                  if 'م' in line_dediac[idx]: #handles years abbreviated with calendar type
                    line_dediac[idx] = line_dediac[idx].replace('م', '')
                    line_dediac.insert(idx + 1, 'ميلادية')
                    k = an.int2str(line_dediac[idx])
                  elif 'ه' in line_dediac[idx]:
                    line_dediac[idx] = line_dediac[idx].replace('ه', '')
                    line_dediac.insert(idx + 1, 'هجرية')
                    k = an.int2str(line_dediac[idx])
                  elif '0' != line_dediac[idx]:
                    k = line_dediac[idx]
                line_dediac[idx] = k

###replace multiple repeated characters with just one-for 3+ repetitions:
              for letter in range(len(line_dediac[idx])): #look at each letter in line
                letter_2 = letter
                while letter_2 < len(line_dediac[idx]) and line_dediac[idx][letter] == line_dediac[idx][letter_2]: #get the index of final repeated letter
                  letter_2 += 1
                if letter_2 > letter + 2: #at least three reps
                  line_dediac[idx] = line_dediac[idx][:letter+1] + line_dediac[idx][letter_2:]

###deal with missing spaces-this only gets a few of the typos
                if letter < len(line_dediac[idx]) -1:
                  if line_dediac[idx][letter] == 'ة' and line_dediac[idx][letter+1] != ' ': #non-final taa marbuta
                    line_dediac[idx] = line_dediac[idx][:letter+1] + ' ' + line_dediac[idx][letter+1:]
                  elif (line_dediac[idx][letter] == 'ا' or line_dediac[idx][letter] == 'أ') and (line_dediac[idx][letter+1] == 'ا' or line_dediac[idx][letter+1] == 'أ'): #double alefs
                    line_dediac[idx] = line_dediac[idx][:letter+1] + ' ' + line_dediac[idx][letter+1:]
                  elif line_dediac[idx][letter] == 'ء' and line_dediac[idx][letter-1] != 'و' and line_dediac[idx][letter+1] != ' ': #non-final hamza (ok if preceding waa)
                    line_dediac[idx] = line_dediac[idx][:letter+1] + ' ' + line_dediac[idx][letter+1:]
###join back up
            line_dediac = ' '.join(line_dediac)

###strip all punctuation

            #line_dediac_2 = line_dediac.translate({ord(i):None for i in '[()\[\]<—>{}/\»«﴾﴿*♪:؛.!\'‘’”“#؟•+%٪\t_،,-]'})
            line_dediac_2 = line_dediac.translate({ord(i):None for i in punctuation})
            line_dediac_2 = line_dediac_2.translate({ord(i):None for i in emoji_list})

###multicharacter punctuation:
            for error in text_errors:
              line_dediac_2 = line_dediac_2.replace(error, ' ') #this will rearrange words bc errors are latin text, presumably returning to original order

###append lines to new list for generating word list
            if len(line_dediac_2) >= 1:
              text.append(line_dediac_2)
            else:
              line_dediac_2 = ' '

#insert modified line back into text
            raw_line = raw_line[:20] + line_dediac_2 + raw_line[-2:]
            processed_copy.append(raw_line)
        else:
          processed_copy.append(raw_line)
  with open(join(output_directory, str(f[:-9] + '_processed.TextGrid')), 'w') as r:
    for raw_line in processed_copy:
      r.write(str(raw_line))
#create word list
  for line_t in text:
    line_t = line_t.split(' ')
    for t in line_t:
      if t not in word_list:
        word_list.append(t)
#dialect predictions
  if dialect_ids == True:
    did = DialectIdentifier.pretrained()
    text = [' '.join(text)]
    predictions_country = did.predict(text, 'country')
    predictions_country = sorted(predictions_country[0][1].items(), key=lambda item: item[1], reverse = True)
    predictions_region = did.predict(text, 'region')
    predictions_region = sorted(predictions_region[0][1].items(), key=lambda item: item[1], reverse = True)
    predictions_city = did.predict(text, 'city')
    predictions_city = sorted(predictions_city[0][1].items(), key=lambda item: item[1], reverse = True)
    file_did = str(f[:-9] + ',' + predictions_country[0][0] + ',' + str(predictions_country[0][1]) + ',' + predictions_region[0][0] + ',' + str(predictions_region[0][1]) + ',' + predictions_city[0][0] + ',' + str(predictions_city[0][1]) + '\n')
    dialect_ids.append(file_did)

#generate dictionary
for t in word_list:
  analysis = analyzer.analyze(t)
  if len(analysis) > 0:
    for i in range(len(analysis)): #{, ` show up in a few entries (probably a carryover from buckwalter transcription). the correct transcription is already in the db, so exclude these values
      if analysis[i]['caphi'] != 'FOREIGN' and analysis[i]['caphi'] != 'DIGIT' and analysis[i]['caphi'] != 'PUNC' and '{' not in analysis[i]['caphi'] and '`' not in analysis[i]['caphi']:
        sent_bw = ar2bw(analysis[i]['diac'])
        base_dict_entry = [t, analysis[i]['caphi']]
        dictionary_entry = str(t + '\t' + analysis[i]['diac'] + '\t' + analysis[i]['pos'] + '\t' + analysis[i]['vox'] + '\t' + analysis[i]['mod'] + '\t' + analysis[i]['cas'] + '\t' + analysis[i]['stt'] + '\t' + sent_bw + '\t' + analysis[i]['caphi'])
        if dictionary_entry not in dictionary_entries:
          dictionary_entries.append(dictionary_entry)
  else:
    oovs.append(str(t + '\n'))


#write files

with open(join(output_directory_dict, 'dictionary_entries.txt'), 'w') as d:
  for dictionary_entry in dictionary_entries:
    d.write(str(str(dictionary_entry) + '\n'))
with open(join(output_directory_dict, 'oovs.txt'), 'w') as t:
  for oov in oovs:
    t.write(oov)
if dialect_ids == True:
  with open(join(output_directory_dict,'dialect_predictions.txt'), 'w') as p:
    for ids in dialect_ids:
      p.write(ids)

# @title
#this code generates dictionary entries in Egyptian Arabic, both for words in the dictionary and on the OOVs list
#read in files
dict_path = join(output_directory_dict, 'dictionary_entries.txt')
oovs_path = join(output_directory_dict, 'oovs.txt')
new_path = '/content/' #for new list of oovs


#set morphology db as egyptian
db = MorphologyDB.builtin_db('calima-egy-r13')
analyzer = Analyzer(db)

#buckwalter to caphi transcription:
caphi = ['b', 't', 'th', 'j', '7', 'kh',
              'd', 'dh', 'r', 'z', 's', 'sh', 's.', 'd.', 't.',
              'dh.', '3', 'gh', 'f', 'k', 'q', 'l', 'm', 'n', 'h', 'w', 'y', 'aa', 'a', 'i', 'u', '2', '_', '.', 'g', '2_a', '2_i', 'u_2', 'a_n', 'u_n', 'i_n', '2_aa']
correspondences = [
#consonants
('T', 't.'),
('*', 'dh'),
('D', 'd.'),
('Z', 'dh.'),
('v', 'th'),
('S', 's.'),
('$', 'sh'),
('x', 'kh'),
('g', 'gh'),
('H', '7'),
('E', '3'),
#hamza
('\'', '2'),
('>', '2_a'),
('<', '2_i'),
('&', 'u_2'),
('}', '2'),
#alif
('|', '2_aa'),
('{', ''),
('`', 'aa'),
#harakat-fatha, damma, kasra are same in bw and caphi
('F', 'a_n'),
('N', 'u_n'),
('K', 'i_n'),
('o', ''),
('p', 'a'),
]

special_chars = ['Y', 'A', '~']


#step 2: read in dictionary and oov lists
new_entries = []
new_oovs = []
def bw_to_caphi (word):
  word = word.strip('\n')
  analysis = analyzer.analyze(word)
  if len(analysis) > 0:
    for i in range(len(analysis)):
      if analysis[i]['pos'] not in ['foreign', 'digit', 'punc']:
        sent_bw = ar2bw(analysis[i]['diac'])
        new_value = []
        for letter in sent_bw:
          new_value.append(letter)
        new_value = '_'.join(new_value) #need to join and then resplit-all bw transcriptions are one letter, but caphi uses multichar transcriptions
        new_value = new_value.split('_')
        for index, letter in enumerate(new_value):
          for bw in range(len(correspondences)):
            if correspondences[bw][0] == letter:
              new_value[index] = correspondences[bw][1]
          if letter in special_chars:
            if letter == 'Y':
              new_value_copy = new_value
              new_value[index] = 'y'
              new_value_copy[index] = 'aa'
            elif letter == 'A':
              if len(new_value) == 1 or new_value[-2] == 'a':
                new_value[index] = 'a'
              else:
                new_value[index] = 'aa'
            elif letter == '~':
              if new_value[index-2] == 'l': #deals with sheddah indicating coronal assimilation
                new_value[index-2] = new_value[index-1]
                new_value[index] = ''
              else:
                new_value[index] = new_value[index-1]
        for index, letter in enumerate(new_value):
          if letter not in caphi:
            if letter == '':
              del new_value[index]
            else:
              print(analysis[i]['diac'], letter, new_value)
        new_value = '_'.join(new_value)
        new_value = new_value.replace('__', '_')
        new_entry = str(word + '\t' + analysis[i]['diac'] + '\t' + analysis[i]['pos'] + '\t' + analysis[i]['vox'] + '\t' + analysis[i]['mod'] + '\t' + analysis[i]['cas'] + '\t' + analysis[i]['stt'] + '\t' + sent_bw + '\t' + new_value)
        if new_entry not in new_entries:
          new_entries.append(new_entry)
  else:
    new_oovs.append(word)

with open(oovs_path, mode = 'r') as oovs:
  for oov in oovs:
    bw_to_caphi(oov)
with open(dict_path, mode = 'r') as d:
  d_read = d.readlines()
  for row in d_read:
    bw_to_caphi(row[0])
  for new_entry in new_entries:
    if new_entry not in d:
      with open(dict_path, 'a') as d2:
        d2.write(str(str(new_entry) + '\n'))
with open(join(new_path, 'new_oovs.txt'), 'w') as n:
  for oov in new_oovs:
    n.write(str(str(oov) + '\n'))

# @title
#filter
filtered_entries = []

with open(dict_path, 'r') as d:
  d = d.readlines()

def filter(d):
  for entry in d:
    entry = entry.strip('\n')
    entry = entry.strip('\'')
    entry = entry.strip('[')
    entry = entry.strip(']')
    entry = entry.split('\t')
		#filter out passives	filter out subjunctives	               filter out case markings
    if entry[3] != 'p' and entry[4] != 's' and entry[5] != 'n' and entry[5] != 'a' and entry[5] != 'g' and entry[6] != 'c':
      if entry[6] == 'd' and (entry[0].startswith('ال') or entry[0].startswith('أل')) and entry[8].startswith('2_a_'):
        new_pron1 = entry[8].split('_')
        new_pron2 = entry[8].split('_')
        new_pron1 = ' '.join(new_pron1[1:])
        new_pron2 = ' '.join(new_pron2[2:])
        new_entry1 = entry[:8]
        new_entry1.append(new_pron1)
        new_entry2 = entry[:8]
        new_entry2.append(new_pron2)
        f = ''
        g = ''
        for c in new_entry1[:-1]:
          f += str(c + '\t')
          f += str(new_entry1[-1] + '\n')
          d.append(f)
        for c in new_entry2[:-1]:
          g += str(c + '\t')
          g += str(new_entry2[-1] + '\n')
          d.append(g)
      entry[8] = entry[8].replace('_', ' ') #replace _ with spaces
      filtered_entry = str(entry[0] + '\t' + entry[8] + '\n') #make new entry
      yield filtered_entry
		#allow all pronouns and fix some other issues where words in dictionary were filtered out inappropriately, resulting in oovs
    elif entry[2] == 'pron' or (entry[2] == 'adj' and (entry[0].endswith('ا') or entry[0].endswith('أ') or entry[0].endswith('آ'))) or (entry[0].endswith('ان') or entry[0].endswith('ين') or entry[0].endswith('ون')):
      entry[8] = entry[8].replace('_', ' ') #replace _ with spaces
      filtered_entry = str(entry[0] + '\t' + entry[8] + '\n') #make new entry
      yield filtered_entry
 #removes passives unless the passive is the only form in the dictionary
    elif entry[3] == 'p':
      for e in d:
        if e[0] == entry[0] and e[3] != 'p':
          break
        else:
          entry[8] = entry[8].replace('_', ' ') #replace _ with spaces
          filtered_entry = str(entry[0] + '\t' + entry[8] + '\n') #make new entry
          yield filtered_entry
#removes the construct/poss/idaafa unless it is the only form in the dictionary; preserves final /t/ in feminine nouns
    elif entry[6] == 'c':
      if (entry[0].endswith('ة') or entry[0].endswith('ه')) and entry[2] == 'noun':
        entry[8] = entry[8].split('_')
        if entry[8][-2:] == ['t', 'a'] or entry[8][-2:] == ['t', 'i'] or entry[8][-2:] == ['t', 'u']:
          entry[8] = entry[8][:-1]
          entry[8] = ' '.join(entry[8])
          entry[8] = entry[8].replace('_', ' ') #replace _ with spaces
          filtered_entry = str(entry[0] + '\t' + entry[8] + '\n') #make new entry
          yield filtered_entry
      else:
        for e in d:
            e = e.split('\t')
            if e[0] == entry[0] and e[6] != 'c':
              break
            else:
              entry[8] = entry[8].replace('_', ' ') #replace _ with spaces
              filtered_entry = str(entry[0] + '\t' + entry[8] + '\n') #make new entry
              yield filtered_entry

#need to run the generator outside of loop
s = filter(d)

#so this works, but if you try to manipulate the generator output at all it will only return generator objects and not output.
with open('/content/filtered_dictionary_entries.tsv', 'w') as g:
  g.writelines(set(s))

# @title
#attempting to find 3-consonant sequences
df = pd.read_csv('/content/filtered_dictionary_entries.tsv', sep = '\t', names = ['ARABIC', 'CAPHI'])
df = df.to_numpy()
df_copy = df
#df_copy['CCC_epenth'] = ' '

consonants = ['b', 't', 'th', 'dj', '7', 'kh',
              'd', 'dh', 'r', 'z', 's', 'sh', 's.', 'd.', 't.',
              'dh.', '3', 'gh', 'f', 'k', 'q', 'l', 'm', 'n', 'h']

new_transcriptions = df_copy.tolist()

#CCC
#for entry in range(len(new_transcriptions)): #for each row
for entry in range(len(new_transcriptions)):
    value = new_transcriptions[entry][1].split() #split the transcription into a list of characters
    for phone in range(len(value)-2):
      if value[phone] in consonants and value[phone+1] in consonants and value[phone+2] in consonants and value[phone] != value[phone+1] and value[phone+1] != value[phone+2]: #find CCCs
        if epenthesis_site == 'CVCC' or epenthesis_site == 'both': #generate new entry-generates entries
            new_entry_CCC = value[:phone+1] + ['i'] + value[phone+1:]
            new_entry_CCC = ' '.join(new_entry_CCC)
            new_entry = [new_transcriptions[entry][0], new_entry_CCC]
            if new_entry not in new_transcriptions:
              	new_transcriptions.append(new_entry)
        if epenthesis_site == 'CCVC' or epenthesis_site == 'both':
            new_entry_CCC = value[:phone+2] + ['i'] + value[phone+2:]
            new_entry_CCC = ' '.join(new_entry_CCC)
            new_entry = [new_transcriptions[entry][0], new_entry_CCC]
            if new_entry not in new_transcriptions:
              	new_transcriptions.append(new_entry)
        #print(new_entry)

'''with open('full_checkpoint_1.csv', 'w') as f1:
	for line in new_transcriptions:
		#line = str(str(line[0] + '\t' + line[1]) + '\n')
		f1.write(str(str(line[0] + '\t' + line[1]) + '\n'))'''

#coda clusters
if coda_cluster_epenthesis == True:
  coda_clusters = []
  for entry in range(len(new_transcriptions)): #for each row
    value = new_transcriptions[entry][1].split()
    if len(value) > 1 and value[-1] in consonants and value[-2] in consonants and value[-1] != value[-2]: #for transcriptions with more than one character, and a non-geminate coda cluster
      new_entry_CC = value[:-1] + ['i'] + value[-1:] #put epenthetic 'i' between CC
      new_entry_CC = ' '.join(new_entry_CC)
      new_entry = [new_transcriptions[entry][0], new_entry_CC]
      if new_transcriptions[entry][1] not in coda_clusters:
          coda_clusters.append(new_transcriptions[entry])
          coda_clusters.append(new_entry)
      if new_entry not in new_transcriptions:
          new_transcriptions.append(new_entry)

row_new_entries = []
for entry in new_transcriptions: #for each row
  #for transcript in entry[1]: transcript = CAPHI
    for letter_ar in range(len(alphabet_letters_ar)): #goes letter by letter in arabic
      if len(alphabet[letter_ar][1]) > 1: #skips phones with no non-MSA variants (خ, ع, ح, ط)
        for letter in range(len(entry[0])): #loops through each Arabic letter in word
          if entry[0][letter] == alphabet_letters_ar[letter_ar]: #if arabic letter in entry matches arabic letter in loop (if not continues loop)
            value = entry[1].split()
            #print(entry[0][letter])
            for phone in range(len(value)): #for letter in transcription
              if value[phone] == alphabet[letter_ar][1][0]: #only changes msa characters
                #print(value[phone])
                for j in range(1, len(alphabet[letter_ar][1])):
                    if phone != 0 and value[phone] == value[phone-1]:
                      continue
                    new_value = value[:phone] + [alphabet[letter_ar][1][j]] + value[phone+1:]
                    #value[phone] = alphabet[letter_ar][1][j] #creates new entry by putting the non-msa character at the phone index
                    if phone != len(value)-1 and new_value[phone] in alphabet[letter_ar][1][1:] and new_value[phone+1] == alphabet[letter_ar][1][0]: #non-initial phones in set of non-MSA variants, previous phone in MSA-same letter has same transcription across word
                      new_value[phone+1] = new_value[phone]
                    new_entry_C = ' '.join(new_value)
                    new_entry = [entry[0], new_entry_C]
                    if new_entry not in new_transcriptions:
                      #print(new_transcriptions.index(entry), len(new_transcriptions))
                      new_transcriptions.append(new_entry)

with open('/content/processed_dict.dict', 'a') as f3:
	for line in new_transcriptions:
		#line = str(str(line[0] + '\t' + line[1]) + '\n')
		f3.write(str(str(line[0] + '\t' + line[1]) + '\n'))

# @title
if monophthongization == True:
  with open('/content/processed_dict.dict', 'r') as f2:
  	f2 = f2.readlines()
  new_entries = []

  for entry in f2:
    entry = entry.strip('\n').split('\t')
    string = entry[1].split(' ')
    for i in range(len(string)-1):
      if string[i] == 'a' and string[i+1] == 'y':
        if string[i+1] == len(string):
          new_string = string[:i] + ['ee']
        elif len(string) > i+2 and string[i+2] != 'a' and string[i+2] != 'i' and string[i+2] != 'u' and string[i+2] != 'aa' and string[i+2] != 'ii' and string[i+2] != 'uu' and string[i+2] != 'y':
          new_string = string[:i] + ['ee'] + string[i+2:]
      elif string[i] == 'a' and string[i+1] == 'w':
        if string[i+1] == len(string):
          new_string = string[:i] + ['oo']
        elif len(string) > i+2 and string[i+2] != 'a' and string[i+2] != 'i' and string[i+2] != 'u' and string[i+2] != 'aa' and string[i+2] != 'ii' and string[i+2] != 'uu' and string[i+2] != 'w':
          new_string = string[:i] + ['oo'] + string[i+2:]
      else:
    	  new_string = string
      if new_string != string:
        new_entry = ' '.join(new_string)
        new_entry = [entry[0], new_entry]
        new_entries.append(new_entry)
  with open('/content/processed_dict.dict', 'a') as f3:
	  for line in new_entries:
		  f3.write(str(str(line[0] + '\t' + line[1]) + '\n'))

# @title
if l_filtering == True:
  df = pd.read_csv('/content/processed_dict.dict', sep = '\t', names = ['ARABIC', 'CAPHI'])
  df = df.to_numpy()
  df = df.tolist()
  i = 0
  lines = []
  for line in df:
    i += 1
    if 'l.' in line[1] and 'لله' not in line[0]:
      df.remove(line)

  with open('/content/processed_dict_l.dict', 'w') as f3:
    for line in df:
      f3.write(str(str(line[0] + '\t' + line[1]) + '\n'))